bmf-san/ggc

- cmd/stash_pull_pop.go
This PR improves the stash-pull-pop functionality by replacing the manual sequence of git stash, git pull, and git stash pop commands with a single git pull --autostash command.
Simplifies the code by leveraging Git's built-in --autostash feature.
Reduces potential errors caused by manual stash/pop handling.
Maintains the same functionality but in a cleaner, more reliable way.
This change improves maintainability and aligns with best practices recommended by Git.
> Chore: Refactor stash-pull-pop to use git pull --autostash for cleaner workflow

- cmd/branch_test.go
- cmd/log_test.go
- cmd/remote_test.go
Closes #30.
Adds tests for `remote`, `branch` and `log` commands as mentioned.
- Added error case tests for `remote` command
- Added boundary value tests for `branch` command
- Added output format tests for `log` command
- Improved overall test coverage and reliability
> test: add test cases for remote, branch, and log commands

- cmd/remote_test.go
- cmd/stash_test.go
This PR fixes several test cases that were failing due to brittle string comparisons using `output[:5] != "Usage"`. `strings.Contains(output, "Usage")` was supposed to be the condition to ensure that usage messages are properly detected since the formatting or prefix changes slightly.
Fixes the following tests:
- TestRemoteer_Remote_Help
- TestRemoteer_Remote_NoArgs
- TestRemoteer_Remote_Add_InsufficientArgs
- TestRemoteer_Remote_Remove_InsufficientArgs
- TestRemoteer_Remote_SetURL_InsufficientArgs
- TestStasher_Stash_Help
- TestStasher_Stash_Unknown
> test: fix test cases failing due to bad string check

- README.md
- install.sh
- test/install.bats
This PR adds a comprehensive installation script to easily install `ggc` and any dependencies, working on various systems.
`install.sh`
- Add multi-method installation supporting both 'go install' and source build
- Implement automatic PATH configuration for Go binary and local install directories
- Add cross-platform support (Linux, macOS, Windows WSL/MSYS/Cygwin)
- Detect and configure shell profiles (Bash, Zsh, Fish)
- Add shell completion wildcard expansion in Go module paths
- Include colored output with progress indicators and error handling
- Provide automatic fallback between installation methods
- Add comprehensive error recovery and user guidance
`test/install.bats`
- Tests ran with `bats` (`bats-core`)
- Add test directory and install.bats file
- Include tests for most …
> feat: add comprehensive installation script

- cmd/status.go
- cmd/status_test.go
This PR changes `status.go` to *always* display the current branch and upstream info (if there is an upstream set for the branch) before the status output.
- Integration with previous function to fetch current branch
- Fallback handling when upstream is not configured
- Tests updated to cover new output
Closes #32.
Example 1 (main):
```
On branch main
Your branch is up to date with 'origin/main'
(git status content)
```
Example 2(HEAD checkout):
```
On branch HEAD
(git status content)
```
> feat: display current branch and upstream info in status output

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
This PR fixes the command format to be consistent in the README and adds linting to the PR template checklist.
> fix: add linting to the PR template and keep command format in README consistent

- README.md
- install.sh
- tools/completions/ggc.fish
- Add fish completion loader to install.sh that dynamically loads from Go module cache
- Create tools/completions/ggc.fish with native fish completion syntax
- Support all ggc subcommands and options with context-aware completions
- Include dynamic completion for branch names and file paths
- Update README with fish completion information
> feat: add fish shell completion support

- Makefile
- README.md
This PR fixes the bug when building `ggc` with `make build`, `ggc version` not showing the version, commit and date variables in it's output.
- Add version, commit, and date variables to full build using ldflags
- Fix 'ggc version' command showing no info on regular build
- Add build-fast target for development without version overhead
- Add run-fast target for quick development cycles
- Update .PHONY targets and README documentation
The regular build now includes proper version information while `build-fast` and `run-fast` provides a quicker option for development iterations.
> fix: ensure version info in build, add fast build commands

- README.md
This PR adds a section to the README about pre-compiled binary availability.
- Prominently feature binary downloads as recommended method
- Add supported platforms/architectures
Closes #66.
> docs: add pre-compiled binary installation section

- README.md
This PR clarifies the dependencies and reformats the command list to a markdown table for better readability.
- Clarified wording around project dependencies
- Replaced long bullet list of available commands with a structured markdown table for better readability and scanning
Closes #57.
> docs: clarify dependencies and reformat command list

- git/errors.go
This PR removes two unused error variables `ErrCleanFiles` and `ErrCleanDirs` from `git/errors.go`. These variables were originally introduced as part of earlier error-handling improvements but are no longer referenced anywhere in the codebase. This cleanup improves code readability and maintainability by removing dead code.
Closes #76.
These error variables were added in #17 but have remained unused since then. Removing them aligns with the current error-handling approach and avoids confusion for future contributors.
> chore: remove unused error variables from git/errors.go

- README.md
- install.sh
- tools/completions/ggc.zsh
This PR adds a native Zsh shell completion script to `tools/completions`.
- Adds a dedicated Zsh completion script at tools/completions/ggc.zsh
- Updates README.md to install script for zsh users
- Update install script to automatically install zsh completion for zsh users
Closes #79.
N/A
This improves the user experience for `Zsh` users by providing native completion for `ggc` commands and subcommands. It replaces the need to rely on `Bash` compatibility mode, enabling context-aware and more reliable completions.
> feat: add native Zsh completion script

- README.md
- cmd/branch_test.go
- cmd/cmd.go
- cmd/cmd_test.go
- cmd/complete_test.go
- cmd/constructor_test.go
- cmd/help.go
- cmd/restore.go
- cmd/restore_test.go
- cmd/status_test.go
- cmd/templates/help.go
- git/git.go
- git/restore.go
- git/restore_test.go
- router/router.go
- router/router_test.go
- tools/completions/ggc.bash
- tools/completions/ggc.fish
- tools/completions/ggc.zsh
This PR adds support for the `ggc restore` command mentioned in a previous issue. 
- Restoring files in the working directory from the index
- Unstaging files (restore from HEAD to index)
- Restoring files from specific commits
- Support for restoring all files or specific files
- Shell completions for bash, zsh, and fish
- Updated tests and added new tests as needed
- Updated documentation accordingly to reflect changes
Closes #74.
N/A
Commands added:
```
ggc restore <file>          Restore file in working directory from index
ggc restore .               Restore all files in working directory from index
ggc restore staged <file>   Unstage file (restore from HEAD to index)
ggc restore staged .        Unstage all files
ggc restore <commit> <file> Restore file from specific commit
```
> feat: add support for `ggc restore` command

- .github/workflows/release-dry-run.yml
- .github/workflows/release.yml
Updated goreleaser-action from 5 to 6.
cf. https://github.com/bmf-san/ggc/pull/99
N/A
N/A
N/A
> chore(deps): bump goreleaser/goreleaser-action from 5 to 6

- cmd/interactive.go
- cmd/interactive_test.go
This PR adds basic command descriptions when in interactive mode for better user experience and ease of use.
- Adds functionality to cmd/interactive.go with a new CommandInfo struct
- Adds a description for each command
- Includes tests for ensuring descriptions work properly
Closes #35.
Used some of the code here #42, with required changes.
PS: sorry for the slowdown in PR's. I'm on vacation for the summer so it'll probably be a bit spotty for now 👍
> feat: Add Basic Command Description to Interactive Mode

- Makefile
This PR focuses on speeding up running `make lint` for faster checks.
- Speeds up running make lint to only go install when needed
N/A
This enhancement reduces the overhead of running `make lint` by optimizing the dependency installation process. Previously, dependencies were installed with `go install` every time `make lint` was invoked, which could be time-consuming especially if you have slow internet and `golangci-lint` was already installed.
> feat: Add installation check for install-tools in Makefile

- git/git_test.go
This PR improves the test coverage as shown for the `git` package.
- improve test coverage for git package by updating `git/git_test.go`
Closes #82.
The test coverage was previously only covering basic situations, but the improvements added covers as stated:
- Error cases for each git command
- Different output format handling
- Edge case testing
- Command timeout scenarios
- Invalid repository states
> test: improve test coverage for git package

- README.md
- cmd/cmd_test.go
- cmd/commit.go
- cmd/commit_test.go
- cmd/complete_test.go
- cmd/help.go
- cmd/interactive.go
- cmd/restore_test.go
- cmd/templates/help.go
- git/commit.go
- git/commit_test.go
- git/git.go
- git/mock.go
- tools/completions/ggc.bash
- tools/completions/ggc.fish
- tools/completions/ggc.zsh
removed "commit tmp" command from codebase, command completion setting files and README
close #119 
none
none
> refactor: remove "commit tmp" command

- README.md
- cmd/cmd.go
- cmd/config.go
- config/config.go
- config/config_test.go
- main.go
- router/router.go
- router/router_test.go
This PR implements user-defined command aliases using the `~/.ggcconfig` file.
- Added support for defining aliases in ~/.ggcconfig.yaml
- Aliases can map to a single command (e.g., `st: status`) or a sequence of commands (e.g., `acp: ["add", "commit", "push"]`)
- Implemented alias parsing and execution in router
- Commands from aliases run sequentially and stop on failure
- Updated config validation and tests to support mixed alias types
- Extended `config` command to display alias configuration in readable format
Closes #64.
Aliases are able to be run depending on user's configuration file in `~/.ggcconfig.yaml`. As an example:
```yaml
aliases:
ac:
- add .
- commit tmp
br: branch
ci: commit
quick:
- status
- add .
- commit tmp
st: status
sync:
- pull current
- add .
- commit tmp
- push …
```
> feat: implement user-defined command aliases via config file

- config/config_test.go
fix the small syntax error due to missing closing brace `}` in `config_test.go` that was making tests fail.
#118
> fix: small syntax error in config_test.go

- README.md
- cmd/branch.go
- cmd/clean.go
- cmd/clean_test.go
- cmd/cmd.go
- cmd/cmd_test.go
- cmd/commit.go
- cmd/commit_test.go
- cmd/complete.go
- cmd/config.go
- cmd/help.go
- cmd/help_test.go
- cmd/hook.go
- cmd/log.go
- cmd/log_test.go
- cmd/pull.go
- cmd/pull_test.go
- cmd/push.go
- cmd/push_test.go
- cmd/reset.go
- cmd/restore.go
- cmd/status.go
- cmd/version.go
- go.mod
- install.sh
- main.go
- router/router.go
- router/router_test.go
- Update Go module path to `github.com/bmf-san/ggc/v4` for v4 support
- Refactor all import paths to use `/v4`
- Clean up tags and release management 
N/A
- Follows Go module versioning rules for v4 and above
- Existing tags and releases have been cleaned up
> feat: Migrate to Go module v4 and update import paths

- cmd/branch_test.go
- cmd/cmd_test.go
- cmd/complete_test.go
- cmd/restore.go
- cmd/restore_test.go
- git/git.go
- git/mock.go
- Guard commit-like detection with Git:
- Prefer git rev-parse --verify --quiet <ref> to classify commit-ish.
- Tighten heuristics as a safe fallback:
- HEAD variants: match HEAD, HEAD^, HEAD~, HEAD@{...} only.
- Refs: accept refs/... and common origin/....
- Hex SHAs: accept 7–64 hex chars (SHA-1/256) without panicking.
- Remove unsafe fixed-index slicing that caused slice-bounds panics.
- Update git client:
- Add RevParseVerify(ref string) bool to git.Clienter and implement in client.
- Update test mocks to satisfy the new interface.
- Add/extend boundary tests:
- Short non-commit strings treated as file paths.
- HEAD/HEAD~1/HEAD@{1}, refs/heads/main, origin/main treated as commit-like.
- 7- and 64-char hex recognized; non-hex rejected.
- Negative case: HEADERS treated as a path (not …
> fix(cmd/restore): prevent panic on short refs in isCommitLike

- .gitignore
- config/config.go
- config/config_test.go
- Validate-before-write: Prevents persisting invalid configs by validating prior to any write.
- Atomic-ish save: Write to a temp file, close it, then rename over the destination. On Windows, remove and replace.
failures.
- Secure permissions: Create config directory with 0700; ensure final file is 0600 on Unix.
- Test added: Ensures Save() does not write a file when validation fails (invalid editor).
closes #145 
N/A
N/A
> fix(config): validate-before-write and atomic save with 0700/0600 perms; Windows safety

- config/config.go
- Token validation:
- GitHub: accept classic gh[opusr]_… and fine‑grained github_pat_… with letters, digits, underscores, and hyphens.
- GitLab: accept optional glpat- prefix; 20–100 [A-Za-z0-9_-].
- Redact token values in validation errors.
- Editor validation:
- Parse the first command token, respecting simple quotes for paths with spaces (e.g., "/Applications/VS Code.app/bin/code" -w).
- If token looks like a path, accept it when it exists; otherwise resolve via PATH.
- Remote validation:
- Allow / in integration.github.default-remote.
- Forbid unsafe patterns: leading/trailing . or /, .., //, spaces, or characters outside [A-Za-z0-9._/-].
- closes #147
N/A
> fix(config): broaden token formats, support quoted editor paths, and refine remote name rules

- README.md
- config/config.go
- config/config_test.go
- go.mod
- go.sum
- Migrate YAML dependency from unmaintained gopkg.in/yaml.v3 to maintained go.yaml.in/yaml/v3.
- Update import paths in `config/config.go` and `config/config_test.go`.
- Ran `make deps`
- Update README.md to reflect the new module path.
- No functional changes intended; configuration parsing behavior remains the same.
closes #149 
N/A
- Rationale: go.yaml.in/yaml/v3 is the actively maintained path for the YAML v3 module, reducing maintenance and supply-chain risk versus the legacy gopkg.in path.
- Scope: Mechanical migration only (imports, module files, docs); no logic changes.
> chore(deps): Migrate to maintained go-yaml version

- cmd/interactive.go
This PR fixes a cyclomatic complexity lint error in the `processCSIFinalByte` function in `cmd/interactive.go`.
**Changes made:**
- Refactored `processCSIFinalByte` function to use the existing `isWordMotionParam` helper function
- Removed duplicate parameter parsing logic that was causing high cyclomatic complexity (11 > 10)
- Simplified the function while maintaining identical functionality
- Reduced code duplication by leveraging existing utility function
The function now has a cyclomatic complexity under the threshold while preserving all existing behavior for CSI sequence processing.
This addresses the lint error that was preventing clean builds:
```
cmd/interactive.go:540:1: cyclomatic: function (*KeyHandler).processCSIFinalByte has cyclomatic complexity 11 (> max enabled 10) …
```
> fix: reduce cyclomatic complexity in processCSIFinalByte function

- cmd/keybinding_parser.go
- cmd/keybinding_parser_test.go
- cmd/keybinding_resolver_test.go
- cmd/keybindings.go
- cmd/keybindings_layers_test.go
- config/config.go
- config/config_test.go
this one is designed to be landed after #189... the diff will not render correctly until that's merged.
- hook keybinding validation into config.Config.Validate, covering profile selection plus global, context, platform, and terminal overrides so invalid entries surface during config load/save.
- mirror the interactive resolver’s parsing rules locally via parseKeyBinding, allowing caret and Emacs notations while avoiding circular imports and providing consistent error messages.
- expand manager load/save tests to exercise keybinding overrides (including array inputs) and confirm failed validation blocks writes; add regression coverage in config/config_test.go.
- note the newly supported formats in cmd/keybindings_layers_test.go to keep resolver tests aligned with the config surface. …
> feat(cmd): add keybindings config

- cmd/interactive.go
- cmd/keybinding_parser.go
- cmd/keybindings.go
- cmd/keybindings_features_test.go
- cmd/keybindings_layers_test.go
- cmd/platform_optimizations_test.go
- cmd/runtime_profile_switch_test.go
- config/config.go
- docs/keybindings-examples.md
- docs/terminal-mapping.md
to test the keybindings feature, clone **this** branch. it is the final branch on the stack (#189, #190, #191) so is feature complete. the others need to be reviewed and merged in order and were broken down to reduce cognitive load during review :) 
- enable runtime profile switching and hot reload hooks so the UI can swap contextual maps without restart (cmd/
keybindings.go:2159, cmd/keybindings.go:2568)
- add exporter/importer pipelines for keybinding configs, including delta exports, backups, and dry-run previews (cmd/
keybindings.go:2845, cmd/keybindings.go:3123)
- surface debug capture utilities and platform-specific optimizations to help map raw escape sequences and per-terminal
tweaks (cmd/keybindings.go:2567, cmd/keybindings.go:3491)
- expand coverage with focused tests for …
> feat(cmd): Keybindings Tooling

- README.md
- cmd/cmd.go
- cmd/cmd_test.go
- cmd/debug_comprehensive_test.go
- cmd/debug_test.go
- cmd/diff_test.go
- cmd/interactive.go
- cmd/interactive_keybinds_test.go
- cmd/interactive_terminal_test.go
- cmd/interactive_test.go
- cmd/keybindings.go
- cmd/keybindings_display_test.go
- cmd/remote_test.go
- cmd/reset_test.go
- cmd/restore_test.go
- cmd/runtime_profile_switch_test.go
- cmd/stash_test.go
- cmd/status_test.go
- cmd/tag_test.go
- cmd/workflow.go
- cmd/workflow_test.go
- config/config.go
- config/config_test.go
- replaced the static interactive help card with dynamic entries sourced from the active key map so customised bindings (e.g. `Ctrl+l`, `Alt+Backspace`) surface automatically (`cmd/interactive.go`, `cmd/keybindings.go`).
- added reusable keystroke display helpers plus unit coverage to keep terminal output in sync across the CLI and UI (`cmd/keybindings_display_test.go`, `cmd/interactive_keybinds_test.go`).
closes #210
N/A
> bug: Keybindings panel does not display real keybinds

- CONTRIBUTING.md
- README.md
- cmd/add_test.go
- cmd/cmd_test.go
- cmd/command/registry.go
- cmd/diff.go
- cmd/diff_test.go
- cmd/help.go
- git/diff.go
- git/diff_test.go
- git/interfaces.go
- internal/testutil/git_client.go
- replaced the old ggc diff dispatcher with a stateful parser that understands modes, summary flags, commit ranges, and path filters, then funnels the assembled argv through DiffWith.
- added DiffWith to the git client surface and refactored the existing helpers (Diff, DiffStaged, DiffHead) to delegate to it for consistency.
- expanded the diff test suite with parser state coverage, helper-unit checks, and execution cases.
closes #110
> feature: Enhanced diff with commit comparison and path filtering

- cmd/interactive.go
- cmd/keybindings.go
- cmd/keybindings_parse_test.go
- config/config.go
adds support for rebinding arrow keys in the interactive mode. Users can now configure custom keybindings for:
- up/Down arrows for list navigation (`move_up`, `move_down`)
- left/Right arrows for cursor movement (`move_left`, `move_right`)
the implementation adds arrow key constructors (`NewUpArrowKeyStroke()`, `NewDownArrowKeyStroke()`, `NewLeftArrowKeyStroke()`, `NewRightArrowKeyStroke()`), updates the parsing logic to handle arrow key strings (e.g., "up", "down", "left", "right"), and refactors the CSI sequence handling to try keybinding-based handling before falling back to default behavior.
closes #218
arrow keys now work with both CSI mode (ESC [ X) and application cursor mode (ESC O X). The default behavior is preserved (arrow keys work as before), but users can now override them …
> feat(cmd): add arrow keys/cursor rebindability

- cmd/cmd.go
ensure the interactive installs SIGINT/SIGTERM handlers atomically by dropping the interim `signal.Reset()` call, deferring `signal.Stop`, and stopping notifications on exit so signals can't be lost.
closes #225
> bug(cmd): Race condition in signal handler

- cmd/branch.go
- config/config.go
- config/config_test.go
- git/branch.go
- git/branch_test.go
- git/commit.go
- git/commit_test.go
introduces upfront validation for high-risk inputs so users get actionable errors instead of git panics: commit and amend commands now reject empty/invalid messages, branch mutations normalise and validate branch names with `git check-ref-format`, and config key lookups enforce well-formed dot paths before traversal. updated command handlers and unit tests cover the new validation paths.
closes #224
> bug(cmd): Introduce input validation for high risk inputs and error clarification

- cmd/cmd.go
- cmd/cmd_test.go
- cmd/keybindings_bridge.go
- internal/interactive/constants.go
- internal/interactive/controller.go
- internal/interactive/interactive_keybinds_test.go
- internal/interactive/interactive_terminal_test.go
- internal/interactive/interactive_test.go
- internal/interactive/interactive_unicode_test.go
- internal/interactive/keybindings_bridge.go
- internal/interactive/new_ui_config_test.go
- internal/interactive/ui_state_test.go
- internal/interactive/workflow.go
- internal/interactive/workflow_test.go
- internal/keybindings/context_manager_test.go
- internal/keybindings/debug_keys_command_test.go
- internal/keybindings/display_test.go
- internal/keybindings/features_test.go
- internal/keybindings/keybindings_test.go
- internal/keybindings/layers_test.go
- internal/keybindings/parse_test.go
- internal/keybindings/parser.go
- internal/keybindings/parser_internal.go
- internal/keybindings/parser_internal_test.go
- internal/keybindings/platform_optimizations_test.go
- internal/keybindings/profile_test.go
- internal/keybindings/resolver_test.go
- internal/keybindings/runtime_profile_switch_test.go
- internal/keybindings/test_helpers_test.go
- extract the interactive UI implementation into `internal/interactive`, leaving `cmd/interactive.go` as a lightweight facade wired through the new controller and renderer.
- split keybinding logic into `internal/keybindings`, expose the necessary bridge in `cmd/keybindings_bridge.go`, and update command wiring to use the new package.
- relocate and refresh interactive/keybinding tests to target the new packages and validate workflow/profile switching behaviour.
part #207 
- modularisation prepares for future waves of the architecture refactor by isolating interactive UI and keybinding concerns under `internal/` while keeping the CLI layer stable.
> arch: Refactor Interactive And Keybindings Architecture (Wave 1)
